### ISSUE TITLE
Add device filter

### ISSUE THREAD

**Issue by bitmerchandise** [damianxd/homebridge-vera#18]
hello,

Would it be possible to add a function to filter devices?
Example: i have many virtual switches in vera for day/night, summer/winter etc.
since, the plugin pulls all devices, i end up with many devices that i would never ask siri to control.

I have seen in other plugins (homebridge-edomoticz) that allow you to import a room only, in vera's case, we would put all homekit devices into a room called homekit and only import that room via its roomID

thank you for considering

**Comment by bigeazy000** [comment]
I agree, this would be a very useful feature. I have some switches in Vera that I would never want to control via homebridge, for example my network cabinet.. I dont want to turn it off by accident or by issuing a global command like "turn lights off".

Thanks for developing homebridge, it is great!

**Comment by damianxd** [comment]
Yeah, it seems like a good addition. I will work on this project during the weekend and see if I can arrange this.

**Comment by bitmerchandise** [comment]
Maybe this can help you out https://github.com/nfarina/homebridge/pull/497

Thank you for doing this, much appreciated

**Comment by CelticWebSolutions** [comment]
Agreed, thus would be a very useful feature.  Some way to edit what devices are sent to homebridge would be extremely useful.  Similar to bigeasy000, if I say all lights off, it turns every switch I have off so my computer systems get switched off without shut down.

Does HomeKit actually have the ability to distinguish a socket vs a light switch? Maybe an ability to edit devices before there sent  to homebridge could be useful?

**Comment by bitmerchandise** [comment]
@CelticWebSolutions that happened to me the other day, Siri misunderstood my command and turned off all lights and plugs, server went down, fun time bringing it all back online :)

**Comment by CelticWebSolutions** [comment]
Hi,  had there been any progress in working out a way to filter devices? Siri unfortunately misunderstood a command for the turn lights off command a few minutes ago and turned off my computer while it was compiling software, unfortunately it's caused corruption of the drive.  It's repairing now, I'm sure it will be fine, I'd just love a way to stop it happening again, even if it's a rather convoluted way of doing it

**Comment by damianxd** [comment]
Sorry for the delay on this guys, I've been busy on my own work and last weekend I did some progress but I'm not done yet. I'm trying to have a config dialogue when you start the standalone version so you can select the rooms you will allow this to work on. So far the configuration works and you can select some variables, but I need to make the listing now. I think I will be done tomorrow or on Sunday

**Comment by bitmerchandise** [comment]
No worries! I understand that you have a life apart from this :)
Glad to hear that you made some progress though.
Thank you for the update

**Comment by damianxd** [comment]
OK, changes are live now. Please download the latest version, delete your config.js and start the standalone version with 
`node VeraLink.js`

and it should prompt some questions about your Vera Device along with a list of rooms where you can ignore whatever you want by adding the ID with comma separated. For the homekit version, just add the config like this:
````
{
    "bridge": {
        "name": "Homebridge",
        "pin": "987-65-432",
        "username": "CC:22:3D:E3:CE:30"
    },
    "platforms": [
        {
            "platform": "Vera",
            "name": "Vera",
            "veraIP": "10.0.1.5",
            "includesensor": false,
            ignorerooms: [20,21,22],
            "securitypoll": 2000,
            "dimmertest": false
        }
    ]
}
````
To get the list of rooms you have, you can check the ID with the standalone version on the first run

**Comment by bitmerchandise** [comment]
Thank you for this

I will try to test it soon

Luis

**Comment by bigeazy000** [comment]
Yes, thanks! 

iPhone. iTypos. iApologize

**Comment by CelticWebSolutions** [comment]
I tried the home bridge version and it done'st take any notice of the ignored rooms.  I had to use "ignore rooms": [0,12],  which was what you said plus the quotation marks.  

So I decided I only use vera anyway so I attempted to us the standalone version, it says
`Error: Cannot find module './config.js'`
but you say to delete that file anyway ?

Any tips please? 

P.s. I'm on a mac

**Comment by CelticWebSolutions** [comment]
When using the home bridge version my config is as follows

`{
    "bridge": {
        "name": "CWSMiniServer",
        "pin": "987-65-432",
        "username": "CC:22:3D:E3:CE:34"
    },
    "platforms": [
        {
            "platform": "Vera",
            "name": "Vera",
            "veraIP": "192.168.1.95",
            "includesensor": true,
	        "ignorerooms": [0,11,16],
            "securitypoll": 2000,
            "dimmertest": true,
            "cardinality": 1
        }
    ]
}`

Still pulls the devices in the ignored rooms though :(

**Comment by damianxd** [comment]
What about the standalone version?

**Comment by CelticWebSolutions** [comment]
If I go to the folder and try to run it as a standalone version it error out saying there is no config file.  I've never use date standalone version before so there wasn't a config file to start with but in your instructions it says to delete it anyway. I'm assuming I'm doing something wrong but can't see what

**Comment by damianxd** [comment]
uhm, that's weird. Are you sure you have the latest version? try to get another git pull

**Comment by snizzleorg** [comment]
So the idea here is that all the devices that i want in homekit I put in a special room? But as far as I know I cannot put devices in more than one room in vera...

Would be easier to ignore devices based on ids I think...

**Comment by damianxd** [comment]
yeah... I thought of that my self, but some users claim they have a big list of devices... 40 to 200 and that is a really big to keep up.
The idea of this was to make it easier to set this up... besides, this original posts says:
"I have seen in other plugins (homebridge-edomoticz) that allow you to import a room only, in vera's case, we would put all homekit devices into a room called homekit and only import that room via its roomID"

If you want, I can add a filter for devices too, but for the moment I don't have the time to make it work with the prompt setup I have made, so you will have to find the IDs your self on Vera's API and add them on the config file

**Comment by CelticWebSolutions** [comment]
Just reinstalling now to ensure everything is up to date.

On a side note, being able to add device ids to ignore would be excellent.  IS it also possible to have devices as switches instead of lights?  In another post somebody mentioned that one of the otters plugins has that ability.

**Comment by CelticWebSolutions** [comment]
Attempting an NPM install as you suggested results in an error and an empty home bridge-vera folder :(

pastebin here 

http://pastebin.com/5xAu6VQA

**Comment by CelticWebSolutions** [comment]
if its' any use to you, you are welcome to remote in and have a look or have a direct chat via Skype / google hangouts / email

**Comment by snizzleorg** [comment]
@damianxd you say ignoring devices as per id is already possible? getting the id from the vera interface is rather easy... The prompt setup wouldn't be necessary

**Comment by snizzleorg** [comment]
anyways thanks for the effort :-)

**Comment by damianxd** [comment]
Your pastebin looks a bit weird... did you use just **npm install**? not **npm install homebridge-vera**, right? did you use it on the homebridge-vera folder?
Also, what are you using, git or npm to use this program?

**Comment by CelticWebSolutions** [comment]
I install home bridge vera with nam install -g homebridge-vera to get a clean install after deleting the original.
Then I went in to the home bridge-vera folder at /usr/local/lib/node_modules/homebridge-vera on my mac and issued the command npm install as you suggest and thats the error I get.

**Comment by snizzleorg** [comment]
Is there any way at the moment to filter devices out via the vera device id?

**Comment by damianxd** [comment]
Device filter added, you can add the list on the config.js file like this:
`module.exports = {
        veraIP:  '10.0.1.5',
        happort: 6200,
        cardinality: 0,
        bridged: true,
        ignorerooms: [1,2,3,5],
        **ignoredevices: [41,42],**
        includesensor: true,
        pincode: '031-45-154',
        dimmertest: false,
        mainHNpath: './node_modules/hap-nodejs'
};
`

To get the list of devices with the IDs you can run `DEBUG=* node VeraLink.js` and you will get the ID after each device, like this:
`...VeraLink ------ Security Sensor Added: Door & Window Sensor 2 **ID:63** +6ms
  VeraLink ------ Switch Added: Luz comedor **ID:32** +4ms
  VeraLink ------ Security Sensor Added: Motion Sensor 8 **ID:64** +2ms
  VeraLink ------ Security Sensor Added: Sensor comedor **ID:60** +1ms
  VeraLink ------ Temp sensor Added: Temperature Sensor 8 **ID:61** +1ms...`

**Comment by bigeazy000** [comment]
I will finally have cycles this week to test this.  I'll let you know how it goes, thank you!!

iPhone. iTypos. iApologize

**Comment by snizzleorg** [comment]
Cool. I will try. is this
```
sudo npm update -g homebridge-vera
```
sufficient to get the latest version? Any way to check which version is installed?

**Comment by bigeazy000** [comment]
I'm trying to install it into a docker container using "npm install -g homebridge-vera" and it seems to be pulling the old version into the container..

**Comment by damianxd** [comment]
There was a problem with the npm version, now it is fixed

**Comment by bigeazy000** [comment]
I was able to pull the new version via npm, thanks! However, it doesnt seem to accept the ignorerooms or ignoredevices strings in my config. Here is the config I have now:
{
        "bridge": {
                "name": "Homebridge",
                "pin": "987-65-432",
                "username": "CC:22:3D:E3:CE:30"
        },
        "platforms": [{
            "platform" : "Vera",
            "name" : "Vera",
            "veraIP" : "172.16.0.10",
            "includesensor" : false,
            "ignorerooms" : [23],
            "dimmertest" : false
        }]
}

**Comment by snizzleorg** [comment]
I have the same problem:

config.json:

```
...
"platforms": [
{
            "platform": "Vera",
            "name": "Vera",
            "veraIP": "192.168.178.187",
            "includesensor": false,
            "ignoredevices": [40,43,48,47,46,38,41,17,26,54,51,66,57,69,29,47,32,44,14,34,65,67],
            "securitypoll": 2000,
            "dimmertest": false
        }
]
```

but the log still shows the devices being added

```
un 17 11:35:12 automator homebridge[386]: Fri, 17 Jun 2016 09:35:12 GMT VeraLink Using url: http://192.168.178.187:3480/data_request?id=lu_sdata
Jun 17 11:35:12 automator homebridge[386]: Fri, 17 Jun 2016 09:35:12 GMT VeraLink ------ Switch Added: Appliance Module ID:48
Jun 17 11:35:12 automator homebridge[386]: Fri, 17 Jun 2016 09:35:12 GMT VeraLink ------ Switch Added: Appliance Module 1 ID:40
Jun 17 11:35:12 automator homebridge[386]: Fri, 17 Jun 2016 09:35:12 GMT VeraLink ------ Switch Added: Appliance Module 2 ID:43
Jun 17 11:35:12 automator homebridge[386]: Fri, 17 Jun 2016 09:35:12 GMT VeraLink ------ Switch Added: Appliance Module 3 ID:46
Jun 17 11:35:12 automator homebridge[386]: Fri, 17 Jun 2016 09:35:12 GMT VeraLink ------ Switch Added: Bath Ceiling Lamp ID:39
Jun 17 11:35:12 automator homebridge[386]: Fri, 17 Jun 2016 09:35:12 GMT VeraLink ------ Security Sensor Added: Bath Flood Sensor ID:17
Jun 17 11:35:12 automator homebridge[386]: Fri, 17 Jun 2016 09:35:12 GMT VeraLink ------ Switch Added: Bathroom Mirror Lamp ID:42
Jun 17 11:35:12 automator homebridge[386]: Fri, 17 Jun 2016 09:35:12 GMT VeraLink ------ Security Sensor Added: bathroom motion ID:26
Jun 17 11:35:12 automator homebridge[386]: Fri, 17 Jun 2016 09:35:12 GMT VeraLink ------ Switch Added: Bathroom Switch 1 ID:38
Jun 17 11:35:12 automator homebridge[386]: Fri, 17 Jun 2016 09:35:12 GMT VeraLink ------ Switch Added: Bathroom Switch 2 ID:41
Jun 17 11:35:12 automator homebridge[386]: Fri, 17 Jun 2016 09:35:12 GMT VeraLink ------ Switch Added: Hall Lamp ID:60
Jun 17 11:35:12 automator homebridge[386]: Fri, 17 Jun 2016 09:35:12 GMT VeraLink ------ Security Sensor Added: hall motion ID:57
Jun 17 11:35:12 automator homebridge[386]: Fri, 17 Jun 2016 09:35:12 GMT VeraLink ------ Security Sensor Added: Hall Smoke Detector ID:69
Jun 17 11:35:12 automator homebridge[386]: Fri, 17 Jun 2016 09:35:12 GMT VeraLink ------ Switch Added: Kitchen Bench Lamp ID:49
Jun 17 11:35:12 automator homebridge[386]: Fri, 17 Jun 2016 09:35:12 GMT VeraLink ------ Security Sensor Added: kitchen motion ID:29
Jun 17 11:35:12 automator homebridge[386]: Fri, 17 Jun 2016 09:35:12 GMT VeraLink ------ Switch Added: Kitchen Relay ID:47
Jun 17 11:35:12 automator homebridge[386]: Fri, 17 Jun 2016 09:35:12 GMT VeraLink ------ Security Sensor Added: kitchen Smoke Sensor ID:32
Jun 17 11:35:12 automator homebridge[386]: Fri, 17 Jun 2016 09:35:12 GMT VeraLink ------ Switch Added: Kitchen Stereo ID:45
Jun 17 11:35:12 automator homebridge[386]: Fri, 17 Jun 2016 09:35:12 GMT VeraLink ------ Switch Added: Kitchen Switch ID:44
Jun 17 11:35:12 automator homebridge[386]: Fri, 17 Jun 2016 09:35:12 GMT VeraLink ------ Security Sensor Added: living motion ID:14
Jun 17 11:35:12 automator homebridge[386]: Fri, 17 Jun 2016 09:35:12 GMT VeraLink ------ Switch Added: Livingroom Stereo ID:50
Jun 17 11:35:12 automator homebridge[386]: Fri, 17 Jun 2016 09:35:12 GMT VeraLink ------ Security Sensor Added: office motion ID:34
Jun 17 11:35:12 automator homebridge[386]: Fri, 17 Jun 2016 09:35:12 GMT VeraLink ------ Security Sensor Added: RFID ID:65
Jun 17 11:35:12 automator homebridge[386]: Fri, 17 Jun 2016 09:35:12 GMT VeraLink ------ Switch Added: TV ID:37
Jun 17 11:35:12 automator homebridge[386]: Fri, 17 Jun 2016 09:35:12 GMT VeraLink ------ Security Sensor Added: Universal binary input 2 ID:67
Jun 17 11:35:12 automator homebridge[386]: Fri, 17 Jun 2016 09:35:12 GMT VeraLink ------ Switch Added: Video Projector ID:61
Jun 17 11:35:12 automator homebridge[386]: Fri, 17 Jun 2016 09:35:12 GMT VeraLink ------ Switch Added: Wall lamp ID:7
```

Im running
```
/usr/local/lib
└── homebridge-vera@0.0.8 
```

**Comment by damianxd** [comment]
Please try again with version 0.0.9, I have added some default parameters and tested ignoredevices deeply.

**Comment by bigeazy000** [comment]
BAM! I can confirm that ignoredevices is working in the new version!! However FYI, it looks like ignorerooms still doesn't work.  Here is what my working config looks like:


        "bridge": {
                "name": "Homebridge",
                "pin": "987-65-432",
                "username": "CC:22:3D:E3:CE:30"
        },
        "platforms": [{
            "platform" : "Vera",
            "name" : "Vera",
            "veraIP" : "172.16.0.10",
            "includesensor" : false,
            "ignoredevices" : [74],
            "dimmertest" : false
        }]
}

THANK YOU!!!

**Comment by damianxd** [comment]
Yeah, ignore rooms still doesn't work because I didn't have the time to write a method to do it. I will try again next weekend since at last I've end up with some work I had pending.

**Comment by wooconstructions** [comment]
Hi Damianxd, thank you for all your time, I am sorry if I missed it somewhere.  Any way of ignore Screens for Vera?
